version: "3"
services:
  redbot:
    image: "phasecorex/red-discordbot:latest"
    container_name: ${CNAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
      restart_policy:
        condition: on-failure
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX}
      - TZ=Europe/Berlin
      - EXTRA_ARGS= --dev --owner ${OID} #--disable-intent presences
    volumes:
      - data:/data
      - config:/config
networks:
  default:
    external:
      name: ${NETWORK}
volumes:
  data: {}
  config: {}
