---
version: '3.8'

services:
  bot:
    image: "phasecorex/red-discordbot:latest"
    mem_limit: 512m
    cpus: 0.5
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      PREFIX: ${PREFIX}
      TZ: "Europe/Berlin"
      REDBOT_VERSION: ${REDBOT_VERSION}
      EXTRA_ARGS: "--dev --owner ${OID}" #--disable-intent presences
    networks:
      - external
    volumes:
      - data:/data
      - config:/config

networks:
  external:
    external: true

volumes:
  data: {}
  config: {}
