version: '3'

services:
  db:
    image: mariadb:10.5
    container_name: ts3_db
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 2048M
    environment:
      MYSQL_ROOT_PASSWORD: "{{ DB_PASSWORD }}"
      MYSQL_DATABASE: teamspeak
    volumes:
      - db-data:/var/lib/mysql
    networks:
      intranet:
        aliases:
          - ts3_db.docker.local

  server:
    image: teamspeak:latest
    container_name: ts3_server
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 2048M
    depends_on:
      - db
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: ts3_db.docker.local
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: "{{ DB_PASSWORD }}"
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - server-data:/var/ts3server/
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    networks:
      intranet:
        aliases:
          - ts3.docker.local
      www:

  bot:
    image: phaldan/jts3servermod:6
    container_name: ts3_bot
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 2048M
    depends_on:
      - db
      - server
    volumes:
      - ${PWD}/config:/JTS3ServerMod/config
      - bot-log:/JTS3ServerMod/log
      - bot-plugins:/JTS3ServerMod/plugins
    networks:
      intranet:

networks:
  intranet:
    external: true
  www:
    external: true

volumes:
  db-data: {}
  server-data: {}
  bot-log: {}
  bot-plugins: {}
