version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    networks:
      - www
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
    - "9000:9000"
    command: -H unix:///var/run/docker.sock

networks:
  www:
    external: true

volumes:
  data: {}
